v14 Rewrite for this src.
JustArtiom/ArtiomsHosting-Bot pull request #8
Opened 2022-08-30 07:30 UTC by TheCtkHoster

v13 -> v14

2022-08-30 07:32 UTC, awaitlol commented
<@918137699842555964> | <@757296951925538856> maybe pull this for me? :point_right: :point_left:

2022-08-30 09:01 UTC, lolollllo requested changes

2022-08-30 09:01 UTC, lolollllo commented on autoRun/updateTicketMessage.js
>          .setColor(`BLUE`)
`.setColor('Blue')`

2022-08-30 09:01 UTC, lolollllo commented on autoRun/updateTicketMessage.js
> +            .setStyle(ButtonStyle.Primary)
This button had the `Secondary` style

2022-08-30 09:01 UTC, lolollllo commented on autoRun/updateTicketMessage.js
>      else channel.send({embeds: toSendEmbed, components: ToSendComponents})
```diff
- embeds: toSendEmbed
+ embeds: [toSendEmbed]

2022-08-30 09:01 UTC, lolollllo commented on autoRun/updateTicketMessage.js
>      else channel.send({embeds: toSendEmbed, components: ToSendComponents})
```diff
- embeds: toSendEmbed
+ embeds: [toSendEmbed]

2022-08-30 09:01 UTC, lolollllo commented on autoRun/wingsStatus.js
>          .setColor(`#677bf9`)
```diff
- .setColor(`#677bf9`)
+ .setColor(0x677bf9)

2022-08-30 09:01 UTC, lolollllo commented on commands/admin/eval.js
>                      	.setColor(`GREEN`)
```diff
- .setColor(`GREEN`)
+ .setColor(`Green`)

2022-08-30 09:01 UTC, lolollllo commented on commands/admin/eval.js
>                      	.setColor(`GREEN`)
```diff
- .setColor(`GREEN`)
+ .setColor(`Green`)

2022-08-30 09:01 UTC, lolollllo commented on commands/admin/eval.js
>                      .setColor(`RED`)
```diff
- .setColor(`RED`)
+ .setColor(`Red`)

2022-08-30 09:01 UTC, lolollllo commented on commands/info/help.js
> +          .setColor(`#677bf9`)
```diff
- .setColor(`#677bf9`)
+ .setColor(`0x677bf9`)

2022-08-30 09:01 UTC, lolollllo commented on commands/info/ping.js
>                      .setColor(`${responce > 300 ? responce > 1000 ? "RED" : "YELLOW" : "GREEN"}`)
```diff
- .setColor(`${responce > 300 ? responce > 1000 ? "RED" : "YELLOW" : "GREEN"}`)
+ .setColor(`${responce > 300 ? responce > 1000 ? "Red" : "Yellow" : "Green"}`)

2022-08-30 09:01 UTC, lolollllo commented on commands/info/snipe.js
>          embed.setColor(`BLUE`)
```diff
- embed.setColor(`BLUE`)
+ embed.setColor(`Blue`)

2022-08-30 09:01 UTC, lolollllo commented on commands/info/snipe.js
> +        snipedMessage.messageContent ? embed.addField({ name: `Message Content`, value:`${snipedMessage.messageContent}`) : null
`addFields()` not `addField()`

2022-08-30 09:01 UTC, lolollllo commented on commands/info/snipe.js
> +        embed.setFooter({ text: ${snipedMessage.member.user.tag} (${snipedMessage.member.user.id}), iconURL: snipedMessage?.member?.user?.displayAvatarURL()});
Missing back quotes

2022-08-30 09:01 UTC, lolollllo commented on commands/server/count.js
> +            .setColor(``#677bf9`)
Extra back quote + 
```diff
- .setColor(`#677bf9`)
+ .setColor(`0x677bf9`)

2022-08-30 09:01 UTC, lolollllo commented on commands/server/create.js
>              .setColor(`#677bf9`)
```diff
- .setColor(`#677bf9`)
+ .setColor(`0x677bf9`)

2022-08-30 09:01 UTC, lolollllo commented on commands/server/create.js
>                  .setColor(`GREEN`)
```diff
- .setColor(`GREEN`)
+ .setColor(`Green`)

2022-08-30 09:01 UTC, lolollllo commented on commands/server/create.js
>                      .setColor('RED')
```diff
- .setColor(`RED`)
+ .setColor(`Red`)

2022-08-30 09:01 UTC, lolollllo commented on commands/server/create.js
>                      .setColor('RED')
```diff
- .setColor(`RED`)
+ .setColor(`Red`)

2022-08-30 09:01 UTC, lolollllo commented on commands/server/create.js
>                      .setColor('RED')
```diff
- .setColor(`RED`)
+ .setColor(`Red`)

2022-08-30 09:01 UTC, lolollllo commented on commands/server/create.js
>                      .setColor('RED')
```diff
- .setColor(`RED`)
+ .setColor(`Red`)

2022-08-30 09:01 UTC, lolollllo commented on commands/server/create.js
>                      .setColor('RED')
```diff
- .setColor(`RED`)
+ .setColor(`Red`)

2022-08-30 09:02 UTC, lolollllo commented
There's more which I'll review later, also would you please run prettier on this

2022-08-31 07:17 UTC, TheCtkHoster commented
Sure. I'll also double check some code.

2022-08-31 07:21 UTC, TheCtkHoster commented
Also please check https://github.com/TheCtkHoster/ArtiomsHosting-Bot-v14/blob/main/commands/info/snipe.js (snipe.js) the embed because I am not too sure if it will work.

2022-08-31 07:48 UTC, TheCtkHoster commented
Updated everything, (including events). Should work now :)

2022-08-31 07:49 UTC, TheCtkHoster commented
![image](https://user-images.githubusercontent.com/69423422/187622736-346e1d32-c69a-4985-b2ce-8faa35cfe94c.png)

Didn't update some files because they already included HEX code in them.

2022-08-31 08:20 UTC, lolollllo commented
> Didn't update some files because they already included HEX code in them.
setColor() takes a number though (or a string if your using the names of the colors) 

https://discord.js.org/#/docs/discord.js/main/typedef/ColorResolvable

2022-08-31 08:24 UTC, TheCtkHoster commented
Hex still works tho so yeah.

2022-08-31 08:27 UTC, lolollllo commented
> Hex still works tho so yeah.
oh kay

2022-08-31 08:28 UTC, TheCtkHoster commented
I'll recheck the code again for `MessageEmbed` and other things where I didn't replace the v13 code with v14.

2022-08-31 08:29 UTC, TheCtkHoster commented
https://github.com/TheCtkHoster/ArtiomsHosting-Bot-v14 (code link btw)

2022-08-31 08:31 UTC, awaitlol commented
Knew it, I forgor to edit https://github.com/TheCtkHoster/ArtiomsHosting-Bot-v14/blob/main/autoRun/updateTicketMessage.js (doing it now)

2022-09-17 01:14 UTC, DIBSTERYT commented
So I just checked through the current running code, it seems that the code that's currently running is vastly different from the current V13 code located within this repository. 

I'll see if we're still looking into a V14 update for this Discord bot, will still need to be decided.

2022-09-17 06:40 UTC, TheCtkHoster commented
> So I just checked through the current running code, it seems that the code that's currently running is vastly different from the current V13 code located within this repository.
> 
> I'll see if we're still looking into a V14 update for this Discord bot, will still need to be decided.

Can you show me where there is v13 code in this repo so I can fix them?

2022-09-22 08:41 UTC, closed without merging